baseURL: https://ryokosuge.com/
languageCode: ja-jp
title: ryokosuge.com
theme: ryokosuge-theme

summaryLength: 70

build:
  writeStats: true
  cachebusters:
    - source: "assets/watching/hugo_stats\\.json"
      target: "styles\\.css"
    - source: "(postcss|tailwind)\\.config\\.js"
      target: "css"

mainSections:
  - research
  - daily-logs
  - english
  - conversations

menu:
  main:
    - identifier: daily-logs
      name: Daily Logs
      url: /daily-logs/
      weight: 1
    - identifier: conversations
      name: Conversations
      url: /conversations/
      weight: 2
    - identifier: research
      name: Research
      url: /research/
      weight: 3
    - identifier: english
      name: English
      url: /english/
      weight: 4